apiVersion: v1
kind: Service
metadata:
  name: testapp-test-0
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: testapp-test-0
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   sidecar.jaegertracing.io/inject: 'true'                                                                                                                                            
  labels:                                                                                                                                                                                                   
    app: testapp-test-0
  name: testapp-test-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-test-0
  template:
    metadata:
      labels:
        app: testapp-test-0
    spec:
      containers:
      - image: ratnadeepb/testapp:jaeger
        imagePullPolicy: Always
        name: testapp-test-0
        ports:
        - containerPort: 5000
      - image: ratnadeepb/micoproxy:latest
        name: micoproxy
        ports:
        - containerPort: 62081
        - containerPort: 62082
        securityContext:
          runAsUser: 2102
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: true
      initContainers:
      - name: mico-init1
        command: [/usr/local/micoinit]
        image: ratnadeepb/micoinit:latest
        securityContext:
          privileged: true
      - name: mico-init2
        command: ['iptables', '-t', 'nat', '-L']
        image: ratnadeepb/micoinit:latest
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: true